//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BHPEntities2 : DbContext
    {
        public BHPEntities2()
            : base("name=BHPEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresy> Adresy { get; set; }
        public virtual DbSet<EwidencjaPracownika> EwidencjaPracownika { get; set; }
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<FirmaPioracaTS> FirmaPioracaTS { get; set; }
        public virtual DbSet<FirmaTS> FirmaTS { get; set; }
        public virtual DbSet<HistoriaOperacji> HistoriaOperacji { get; set; }
        public virtual DbSet<Kontrahenci> Kontrahenci { get; set; }
        public virtual DbSet<Obowie> Obowie { get; set; }
        public virtual DbSet<Odziez> Odziez { get; set; }
        public virtual DbSet<OkresUzywalnosciTS> OkresUzywalnosciTS { get; set; }
        public virtual DbSet<OperatorzyTS> OperatorzyTS { get; set; }
        public virtual DbSet<Pozycje> Pozycje { get; set; }
        public virtual DbSet<PozycjeFaktury> PozycjeFaktury { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Rodzaje> Rodzaje { get; set; }
        public virtual DbSet<Rozmiary> Rozmiary { get; set; }
        public virtual DbSet<SposobyPlatnosci> SposobyPlatnosci { get; set; }
        public virtual DbSet<StanowiskoTS> StanowiskoTS { get; set; }
        public virtual DbSet<Statusy> Statusy { get; set; }
        public virtual DbSet<Towary> Towary { get; set; }
        public virtual DbSet<TypKategoriObowia> TypKategoriObowia { get; set; }
        public virtual DbSet<TypKategoriTS> TypKategoriTS { get; set; }
        public virtual DbSet<WydzialyTS> WydzialyTS { get; set; }
        public virtual DbSet<Zwolnienia> Zwolnienia { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
