//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EwidencjaPracownika
    {
        public long IdPracownika { get; set; }
        public Nullable<long> IdStanowiska { get; set; }
        public Nullable<long> IdFirmy { get; set; }
        public Nullable<long> IdWydzilu { get; set; }
        public Nullable<long> IdOdziezy { get; set; }
        public Nullable<long> IdObowia { get; set; }
        public Nullable<long> IdRozmaru { get; set; }
        public Nullable<long> IdFirmyPioracej { get; set; }
        public Nullable<bool> CzyZdane { get; set; }
    
        public virtual FirmaPioracaTS FirmaPioracaTS { get; set; }
        public virtual FirmaTS FirmaTS { get; set; }
        public virtual Obowie Obowie { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rozmiary Rozmiary { get; set; }
        public virtual StanowiskoTS StanowiskoTS { get; set; }
        public virtual WydzialyTS WydzialyTS { get; set; }
        public virtual Odziez Odziez { get; set; }
    }
}
