//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaPioracaTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaPioracaTS()
        {
            this.EwidencjaPracownika = new HashSet<EwidencjaPracownika>();
        }
    
        public long IdFirmyPioracej { get; set; }
        public string Nazwa { get; set; }
        public string Kod { get; set; }
        public Nullable<System.DateTime> DataUtworzenia { get; set; }
        public Nullable<System.DateTime> DataModyfikacji { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
        public string KtoUtorzyl { get; set; }
        public string KtoZmodyfikowal { get; set; }
        public string KtoUsunal { get; set; }
        public Nullable<int> IdOperatora { get; set; }
        public Nullable<bool> czyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EwidencjaPracownika> EwidencjaPracownika { get; set; }
        public virtual OperatorzyTS OperatorzyTS { get; set; }
        public virtual OperatorzyTS OperatorzyTS1 { get; set; }
    }
}
