//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaOperacji
    {
        public int IdOperacji { get; set; }
        public string Kod_NrOperacji { get; set; }
        public string RodzajOperacji { get; set; }
        public Nullable<int> IdOperatora { get; set; }
        public Nullable<System.DateTime> DataUtorzenia { get; set; }
        public Nullable<System.DateTime> DataModyfikacji { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
        public string KtoUtorzyl { get; set; }
        public string KtoZmodyfikowal { get; set; }
        public string KtoUsunal { get; set; }
    }
}
