//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obowie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obowie()
        {
            this.EwidencjaPracownika = new HashSet<EwidencjaPracownika>();
            this.Pozycje = new HashSet<Pozycje>();
        }
    
        public long IdObowia { get; set; }
        public string NazwaObowia { get; set; }
        public Nullable<long> IdRozmiaru { get; set; }
        public Nullable<System.DateTime> DataUtworzenia { get; set; }
        public Nullable<System.DateTime> DataModyfikacji { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
        public string KtoUtorzyl { get; set; }
        public string KtoZmodyfikowal { get; set; }
        public string KtoUsunal { get; set; }
        public Nullable<int> IdOperatora { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string Rozmiar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EwidencjaPracownika> EwidencjaPracownika { get; set; }
        public virtual OperatorzyTS OperatorzyTS { get; set; }
        public virtual Rozmiary Rozmiary { get; set; }
        public virtual TypKategoriObowia TypKategoriObowia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozycje> Pozycje { get; set; }
    }
}
