//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odziez
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odziez()
        {
            this.Pozycje = new HashSet<Pozycje>();
            this.EwidencjaPracownika = new HashSet<EwidencjaPracownika>();
        }
    
        public long IdOdziezy { get; set; }
        public Nullable<long> idKategori { get; set; }
        public Nullable<System.DateTime> DataUtworzenia { get; set; }
        public Nullable<System.DateTime> DataModyfikacji { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
        public Nullable<System.DateTime> KtoUtorzyl { get; set; }
        public Nullable<System.DateTime> KtoZmodyfikowal { get; set; }
        public Nullable<System.DateTime> KtoUsunal { get; set; }
        public Nullable<int> IdOperatora { get; set; }
        public Nullable<bool> czyAktywny { get; set; }
        public string NazwaOdziezy { get; set; }
        public string Rozmiar { get; set; }
    
        public virtual OperatorzyTS OperatorzyTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozycje> Pozycje { get; set; }
        public virtual TypKategoriTS TypKategoriTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EwidencjaPracownika> EwidencjaPracownika { get; set; }
    }
}
