//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkresUzywalnosciTS
    {
        public int IdOkresuUzywalnosci { get; set; }
        public Nullable<System.DateTime> DataUzywalnosci { get; set; }
        public Nullable<System.DateTime> DoZuzycia { get; set; }
    }
}
