//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozycje
    {
        public long IdPozycji { get; set; }
        public Nullable<long> IdPracownika { get; set; }
        public Nullable<long> IdObowia { get; set; }
        public Nullable<long> IdOziezy { get; set; }
        public Nullable<int> IloscObowia { get; set; }
        public Nullable<int> IloscOdziezy { get; set; }
    
        public virtual Obowie Obowie { get; set; }
        public virtual Odziez Odziez { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
