//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownicy()
        {
            this.Pozycje = new HashSet<Pozycje>();
        }
    
        public long IdPracownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<long> Stanowisko { get; set; }
        public Nullable<long> IdWydzial { get; set; }
        public Nullable<long> IdFirmy { get; set; }
        public string tech1 { get; set; }
        public Nullable<int> idOperatora { get; set; }
        public Nullable<System.DateTime> DataUtorzenia { get; set; }
        public Nullable<System.DateTime> DataModyfikacji { get; set; }
        public Nullable<System.DateTime> DataZatrudnienia { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
        public Nullable<System.DateTime> DataZwolnienia { get; set; }
        public string KtoUtworzyl { get; set; }
        public string KtoZmodyfikowal { get; set; }
        public string KtoUsunal { get; set; }
        public Nullable<bool> czyZatrudniony { get; set; }
        public Nullable<bool> czyZwolniony { get; set; }
        public Nullable<int> IdOdziezy { get; set; }
        public Nullable<int> IdObowia { get; set; }
    
        public virtual EwidencjaPracownika EwidencjaPracownika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozycje> Pozycje { get; set; }
        public virtual FirmaTS FirmaTS { get; set; }
        public virtual StanowiskoTS StanowiskoTS { get; set; }
    }
}
