//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypKategoriTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypKategoriTS()
        {
            this.TypKategoriObowia = new HashSet<TypKategoriObowia>();
            this.Odziez = new HashSet<Odziez>();
        }
    
        public long IdKategori { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DataUtorzenia { get; set; }
        public Nullable<System.DateTime> DataModyfikcji { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
        public string KtoUtorzyl { get; set; }
        public string KtoZmodyfikowal { get; set; }
        public string KtoUsunal { get; set; }
        public Nullable<int> idOperatora { get; set; }
    
        public virtual OperatorzyTS OperatorzyTS { get; set; }
        public virtual OperatorzyTS OperatorzyTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypKategoriObowia> TypKategoriObowia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odziez> Odziez { get; set; }
    }
}
