//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHP.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WydzialyTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WydzialyTS()
        {
            this.EwidencjaPracownika = new HashSet<EwidencjaPracownika>();
        }
    
        public long IdWydzialu { get; set; }
        public string NazwaWydzialu { get; set; }
        public string KodWydzialu { get; set; }
        public Nullable<System.DateTime> DataUtworzenia { get; set; }
        public Nullable<System.DateTime> DataModyfikacji { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
        public Nullable<int> IdOperatora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EwidencjaPracownika> EwidencjaPracownika { get; set; }
        public virtual OperatorzyTS OperatorzyTS { get; set; }
    }
}
